### ISSUE TITLE
Implement standalone chat detection API for text

### ISSUE THREAD

**Issue by evaline-ju** [foundation-model-stack/fms-guardrails-orchestrator#210]
## Description

As a followup to #195, as an orchestrator developer, I want to implement the changes for the updated API, so that I can provide standalone detections on chat. This endpoint is designed for detectors working on full chat histories

### Tasks
1. Implement standalone detector endpoint `/text/detection/chat` (accepting chat history request) in orchestrator
2. Add http client for `detection_chat`
3. Test with dummy detector that works on full chat histories

## Acceptance Criteria

- [ ] Unit tests cover new/changed code
- [ ] Examples build against new/changed code
- [ ] READMEs are updated
- [ ] Type of [semantic version](https://semver.org/) change is identified

**Comment by mdevino** [comment]
The [API](https://foundation-model-stack.github.io/fms-guardrails-orchestrator/?urls.primaryName=Detector+API#/default/chat_analysis_unary_handler_api_v1_text_chat_post) wasn't very clear o a few things to me, so I'm looking [here](https://platform.openai.com/docs/api-reference/chat).

1. Do we need to support deprecated fields (Assistant message's `function_call`, Function message)?

![image](https://github.com/user-attachments/assets/acb23c1c-4011-4de0-8b42-bd5bee6e7976)


2. Will we support all modalities for this endpoint? e.g.: For User messages' `content` array variant, will we support both text and image?

![image](https://github.com/user-attachments/assets/89d3bbd4-b56f-4bf5-b0a8-20cd760ab3d2)
