### ISSUE TITLE
Implement real liveness and readiness endpoints

### ISSUE THREAD

**Issue by gkumbhat** [foundation-model-stack/fms-guardrails-orchestrator#39]
### Description

Currently we a health check endpoint which is stubbed out version. We need to implement real health check endpoint that is able to measure health of the server.

### Tasks
- [ ] Figure out how to measure liveness of orchestr8 server
- [ ] Implement liveness endpoint 
- [ ] Figure out how to measure readiness of orchestr8 server
- [ ] implement liveness endpoint

**Comment by gkumbhat** [comment]
Brainstorming a bit on this topic:

- **Liveness** 
    - we want this probe to help us / kubernetes check if the server stay up and running
    - Potential solutions:
        - Make a call to server and see if it is able to accept request (healthcheck endpoint would suffice)
- **Readiness**
    - we want this probe to help us / k8 check if the server is ready to take connections and serve requests.
    - To start with, we can check if the detector is able to connect / call out to chunker or not.

**Comment by gkumbhat** [comment]
>  is the idea here to make sure we test with an expected available chunker that we parse the list of configured detectors and check a call to the particular chunker?
@evaline-ju yes, precisely
